# Generated by Django 6.0.7 on 2026-07-25 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id_child', models.IntegerField(primary_key=True, serialize=False)),
                ('removal_date', models.DateField()),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('age_at_removal', models.IntegerField(blank=True, null=True)),
                ('most_recent_age', models.IntegerField(blank=True, null=True)),
                ('removal_county', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id_provider', models.IntegerField(primary_key=True, serialize=False)),
                ('license_start_date', models.DateField()),
                ('license_end_date', models.DateField()),
                ('county_provider', models.CharField(max_length=100)),
                ('n_days_licensed', models.IntegerField()),
                ('n_days_active', models.IntegerField()),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_start_date', models.DateField()),
                ('placement_end_date', models.DateField()),
                ('resource_type_on_this_placement', models.CharField(max_length=100)),
                ('placement_index', models.IntegerField()),
                ('removal_county', models.CharField(max_length=100)),
                ('placement_county', models.CharField(max_length=100)),
                ('placement_length', models.IntegerField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='main.child')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placements', to='main.provider')),
            ],
        ),
    ]
